__version__ = '0.1'
__author__ = ('David Dunn')

import sys, argparse

def generateHeader():
    header = '#'*80
    header += '\n# Config automatically generated by %s version %s'%(__name__, __version__)
    header += '\n%s'%('#'*80)
    header += '\n\n'
    return header

def writeObject(obj, name):
    diff = obj
    output = 'import %s\n'%obj.__class__.__module__
    # I'm not doing anything about arguments, but we could use inspect.getargspec() if we wanted
    output += '%s = %s.%s()\n'%(name, obj.__class__.__module__, obj.__class__.__name__) 
    default = obj.__class__()
    diff = objectDiff(obj, default)
    for k in [i for i in diff.__dir__() if i[:2] != '__']:
        output += '%s.%s = %s\n'%(name,k,getattr(obj,k))
    return output

def objectDiff(obj, other):
    diff = type('', (), {})()
    for k in [i for i in obj.__dir__() if i[:2] != '__']:
        if not hasattr(other, k) or getattr(other,k) != getattr(obj,k):
            setattr(diff, k, getattr(obj,k))
    return diff

def configDiff(config, other):
    # not going to look for removed items - that is not the point
    diff = type('', (), {})()
    for k,v in config.__dict__.items():
        #print(k)
        if not hasattr(other, k) or getattr(other,k) != v:
            setattr(diff, k, v)
    return diff

def copyModule(old):
    new = type(old)(old.__name__, old.__doc__)
    new.__dict__.update(old.__dict__)
    for k,v in new.__dict__.items():
        if isinstance(v, dict):
            new.__dict__[k] = copy.copy(v)
    return new

def loadDict(configDict):
    config = type('', (), {})()
    for k,v in configDict.items():
        setattr(config, k, v)
    return config

def saveModule(file, strings):
    header = generateHeader()
    with open(file, 'w') as f:
        f.write(header)
        for s in strings:
            f.write(s)

def loadModule(file, name='config'):
    if sys.version_info[0] == 3:
        import importlib.util
        spec = importlib.util.spec_from_file_location(name, file)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
    elif sys.version_info[0] == 2:
        import imp
        module = imp.load_source(name,file)
    return module
    
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--var', nargs='*', action='append', help='A varaible and value pair')
    args = parser.parse_args()
    config = loadModule('config.py')
    if args.var:
        for var in args.var:
            dtype = type(getattr(config, var[0]))
            if len(var) == 2:
                setattr(config, var[0], dtype(var[1]))
